In [69]:
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

data = pd.read_csv("/content/dataset.csv")

df1 = pd.DataFrame(data)

In [15]:
df1.head(10)

   meanfreq        sd    median       Q25  ...    maxdom   dfrange   modindx  label
0  0.059781  0.064241  0.032027  0.015071  ...  0.007812  0.000000  0.000000   male
1  0.066009  0.067310  0.040229  0.019414  ...  0.054688  0.046875  0.052632   male
2  0.077316  0.083829  0.036718  0.008701  ...  0.015625  0.007812  0.046512   male
3  0.151228  0.072111  0.158011  0.096582  ...  0.562500  0.554688  0.247119   male
4  0.135120  0.079146  0.124656  0.078720  ...  5.484375  5.476562  0.208274   male
5  0.132786  0.079557  0.119090  0.067958  ...  2.726562  2.718750  0.125160   male
6  0.150762  0.074463  0.160106  0.092899  ...  5.312500  5.304688  0.123992   male
7  0.160514  0.076767  0.144337  0.110532  ...  0.539062  0.531250  0.283937   male
8  0.142239  0.078018  0.138587  0.088206  ...  2.164062  2.156250  0.148272   male
9  0.134329  0.080350  0.121451  0.075580  ...  4.695312  4.679688  0.089920   male

[10 rows x 21 columns]

In [16]:
df1.tail(10)

      meanfreq        sd    median  ...   dfrange   modindx   label
3158  0.183667  0.040607  0.182534  ...  3.414062  0.166503  female
3159  0.168794  0.085842  0.188980  ...  5.875000  0.268617  female
3160  0.151771  0.089147  0.185970  ...  4.000000  0.192220  female
3161  0.170656  0.081237  0.184277  ...  0.726562  0.336918  female
3162  0.146023  0.092525  0.183434  ...  2.984375  0.258924  female
3163  0.131884  0.084734  0.153707  ...  4.203125  0.161929  female
3164  0.116221  0.089221  0.076758  ...  3.640625  0.277897  female
3165  0.142056  0.095798  0.183731  ...  2.929688  0.194759  female
3166  0.143659  0.090628  0.184976  ...  3.585938  0.311002  female
3167  0.165509  0.092884  0.183044  ...  0.546875  0.350000  female

[10 rows x 21 columns]

In [19]:
y = df1.iloc[:,-1]

In [29]:
y

0         male
1         male
2         male
3         male
4         male
         ...
3163    female
3164    female
3165    female
3166    female
3167    female
Name: label, Length: 3168, dtype: object

In [39]:
X = df1.iloc[:,[i for i in range(20)]]

In [40]:
X

      meanfreq        sd    median  ...    maxdom   dfrange   modindx
0     0.059781  0.064241  0.032027  ...  0.007812  0.000000  0.000000
1     0.066009  0.067310  0.040229  ...  0.054688  0.046875  0.052632
2     0.077316  0.083829  0.036718  ...  0.015625  0.007812  0.046512
3     0.151228  0.072111  0.158011  ...  0.562500  0.554688  0.247119
4     0.135120  0.079146  0.124656  ...  5.484375  5.476562  0.208274
...        ...       ...       ...  ...       ...       ...       ...
3163  0.131884  0.084734  0.153707  ...  4.210938  4.203125  0.161929
3164  0.116221  0.089221  0.076758  ...  3.679688  3.640625  0.277897
3165  0.142056  0.095798  0.183731  ...  2.937500  2.929688  0.194759
3166  0.143659  0.090628  0.184976  ...  3.593750  3.585938  0.311002
3167  0.165509  0.092884  0.183044  ...  0.554688  0.546875  0.350000

[3168 rows x 20 columns]

In [48]:
le = preprocessing.LabelEncoder()
le.fit(["male","female"])
y_decoded = le.transform(y)

In [51]:
scaler = preprocessing.StandardScaler()
scaler.fit(X)
X_standarted = scaler.transform(X)

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X_standarted,y_decoded,test_size=0.2,train_size = 0.8)

In [73]:
clf = make_pipeline( SVC(kernel = 'linear'))
clf.fit(X_train, y_train)

Pipeline(steps=[('svc', SVC(kernel='linear'))])

In [81]:
predicted = clf.predict(X_test)
expected = y_test

In [82]:
accuracy_score(predicted,expected)

0.9716088328075709

In [83]:
clfd = make_pipeline( SVC(kernel = 'rbf'))
clfd.fit(X_train, y_train)

Pipeline(steps=[('svc', SVC())])

In [84]:
predictedf = clfd.predict(X_test)
expectedf = y_test

In [85]:
accuracy_score(predictedf,expectedf)

0.9794952681388013